print( (lambda x: x**2)(int(input()))
)
print( (lambda x: x**3)(int(input()))
)
print( (lambda x: x**4)(int(input()))
)
print( (lambda x: x**5)(int(input()))
)
print( (lambda x: x**6)(int(input()))
)
print( (lambda x: x**7)(int(input()))
)
print( (lambda x: x**8)(int(input()))
)
print( (lambda x: x**9)(int(input()))
)
print( (lambda x: x**10)(int(input()))
)